import { CameraNode } from '../types/traffic';

// Sample real-world junctions in Vijayawada, Andhra Pradesh, India
export const VIJAYAWADA_CAMERAS: CameraNode[] = [
  {
    id: 'CAM-VIJ-01',
    name: 'Benz Circle Flyover North Approach',
    lat: 16.5005,
    lng: 80.6480,
    junction: 'Benz Circle',
    status: 'active',
    congestionLevel: 'high',
    vehicleCount: 78,
    avgSpeedKmH: 22,
    fps: 15,
    lastPlate: 'AP 16 CQ 4821',
  },
  {
    id: 'CAM-VIJ-02',
    name: 'MG Road - Siddhartha Junction',
    lat: 16.5062,
    lng: 80.6401,
    junction: 'MG Road / Siddhartha',
    status: 'active',
    congestionLevel: 'moderate',
    vehicleCount: 52,
    avgSpeedKmH: 34,
    fps: 15,
    lastPlate: 'AP 16 EH 2004',
  },
  {
    id: 'CAM-VIJ-03',
    name: 'Ramavarappadu Ring (NH16 Junction)',
    lat: 16.5268,
    lng: 80.6729,
    junction: 'Ramavarappadu Ring',
    status: 'active',
    congestionLevel: 'low',
    vehicleCount: 39,
    avgSpeedKmH: 48,
    fps: 15,
    lastPlate: 'AP 39 TK 9812',
  },
  {
    id: 'CAM-VIJ-04',
    name: 'Police Control Room (PCR) Junction',
    lat: 16.5134,
    lng: 80.6192,
    junction: 'PCR Circle',
    status: 'active',
    congestionLevel: 'high',
    vehicleCount: 84,
    avgSpeedKmH: 18,
    fps: 15,
    lastPlate: 'TS 09 FA 1010',
  },
  {
    id: 'CAM-VIJ-05',
    name: 'Pandit Nehru Bus Station (PNBS) Approach',
    lat: 16.5167,
    lng: 80.6125,
    junction: 'PNBS Entrance',
    status: 'active',
    congestionLevel: 'moderate',
    vehicleCount: 61,
    avgSpeedKmH: 26,
    fps: 15,
    lastPlate: 'AP 16 Z 5543',
  },
  {
    id: 'CAM-VIJ-06',
    name: 'Kanaka Durga Varadhi South Ramp',
    lat: 16.4950,
    lng: 80.6083,
    junction: 'Varadhi Bridge Approach',
    status: 'active',
    congestionLevel: 'low',
    vehicleCount: 44,
    avgSpeedKmH: 52,
    fps: 15,
    lastPlate: 'AP 16 BD 7711',
  },
  {
    id: 'CAM-VIJ-07',
    name: 'Gollapudi Bypass - NH65 Junction',
    lat: 16.5412,
    lng: 80.5778,
    junction: 'Gollapudi Ring',
    status: 'active',
    congestionLevel: 'moderate',
    vehicleCount: 47,
    avgSpeedKmH: 42,
    fps: 15,
    lastPlate: 'KA 03 MH 8021',
  },
  {
    id: 'CAM-VIJ-08',
    name: 'Governorpet Eluru Road Crossing',
    lat: 16.5140,
    lng: 80.6275,
    junction: 'Governorpet Square',
    status: 'active',
    congestionLevel: 'high',
    vehicleCount: 71,
    avgSpeedKmH: 19,
    fps: 15,
    lastPlate: 'DL 01 AB 9942',
  },
];

// Distance matrix (in km) between selected cameras to check impossible travel times
export const CAMERA_DISTANCES_KM: Record<string, Record<string, number>> = {
  'CAM-VIJ-01': { 'CAM-VIJ-02': 1.4, 'CAM-VIJ-03': 4.1, 'CAM-VIJ-04': 3.5, 'CAM-VIJ-08': 2.3 },
  'CAM-VIJ-02': { 'CAM-VIJ-01': 1.4, 'CAM-VIJ-04': 2.4, 'CAM-VIJ-08': 1.6 },
  'CAM-VIJ-03': { 'CAM-VIJ-01': 4.1, 'CAM-VIJ-02': 4.8 },
  'CAM-VIJ-04': { 'CAM-VIJ-05': 0.8, 'CAM-VIJ-06': 2.1, 'CAM-VIJ-08': 0.9 },
  'CAM-VIJ-05': { 'CAM-VIJ-04': 0.8, 'CAM-VIJ-06': 2.5 },
  'CAM-VIJ-06': { 'CAM-VIJ-04': 2.1, 'CAM-VIJ-05': 2.5 },
  'CAM-VIJ-07': { 'CAM-VIJ-04': 5.2, 'CAM-VIJ-05': 4.6 },
  'CAM-VIJ-08': { 'CAM-VIJ-01': 2.3, 'CAM-VIJ-02': 1.6, 'CAM-VIJ-04': 0.9 },
};
